name: evento acionado no push
on: 
  push:
  schedule: 
    - cron: "* 1 * * *"

jobs:
  build: 
    runs-on: ubuntu-lates
    steps:
        - name: Checkout do código
          uses: actions/checkout@v3

        - name: Rodar script ou comando
          uses: actions/setup-dotnet@v3
          with:
          dotnet-version: '8.0.x'  

        - name: Restaurar dependências
          run: dotnet restore github4women/github4women.csproj

        - name: Build do projeto
          run: dotnet build github4women/github4women.csproj --no-restore --configuration Release

  