name: evento acionado no push
on: 
  push
  schedule: 
    - cron: "* 1 * * *"

jobs:
  build: 
    runs-on: ubuntu-lates
    steps:
      - name: Criar o webapp
        run: dotnet new webapp -n github4women

      - name: Baixar as dependências
        run: dotnet restore **/*.csproj
    
      - name: Compilar o webapp
        run: dotnet build **/*.csproj --no-restore 

      - name: Rodar o wepapp
        run: dotnet run --project **/*.csproj 


  