name: evento acionado no push
on: push
schedule: 
  - cron: "* 1 * * *"

jobs:
  build: 
    runs-on: ubuntu-lates
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: '6.0.x'
    
      - name: Build with dotnet
        run: dotnet buils --configuration release    